general:
  run_name: ${now:%Y%m%d_%H%M%S}
  outputs: ${hydra:runtime.output_dir}
  random_state: 42
  seed: 42
  output_path: 'outputs/${general.run_name}'
  retry_invalid_predictions: true  # Default value is false
  logging:
    save_prompts: true  # Whether to save prompts
    save_responses: true  # Whether to save responses
    log_path: 'logs'  # Log save path
    log_level: 'DEBUG'  # Log level setting
data:
  name: "isear"  # Dataset name (isear, custom, etc.)
  n_samples: 10 #100 # Number of samples to use (-1 for all)
  default_emotion: "unknown"
  train_size: 0.8
  val_size: 0.2
  column_mapping:
    text: "SIT"
    emotion: "EMOT"
  datasets:
    isear:
      urls:
        - "https://raw.githubusercontent.com/sinmaniphel/py_isear_dataset/master/isear.csv"
      required_columns: ["SIT", "EMOT"]
      separator: "|"
      path: 'data/isear/isear.csv'
      labels: ['joy', 'fear', 'anger', 'sadness', 'disgust', 'shame', 'guilt']
      
      emotions:
        # 1-7 in order of emotion classes
        classes: ["joy", "fear", "anger", "sadness", "disgust", "shame", "guilt"]
  exclude_length: 77
  exclude_phrases:
    - "no response"
    - "can not think of anything just now"
    - "can not think of any situation"
    - "can not remember"
    - "never experienced"
    - "never felt the emotion"
    - "i have never felt this emotion"
    - "none"
    - "blank"
model:
  type: "ollama" #"upstage" #"anthropic"  # "openai" / "ollama" / "upstage" / "anthropic"
  name: "llama3.2" #"sebdg/emotional_llama" #"solar-1-mini-chat" #"solar-1-mini-chat" #"llama3.2" #"solar-1-mini-chat" # "claude-3-sonnet-20240229" #"llama3.2" #"qwen2.5" #"sebdg/emotional_llama" #"hf.co/tensorblock/Emotion-LLaMA-GGUF"  #"claude-3-sonnet-20240229"  # Update Claude 3 model name
  #claude-3-5-sonnet-20241022
  #'gpt-4o' 
   #"deepseek-r1" #
  max_tokens: 2000 #200
  temperature: 0.3
  use_template: false #true #true
  use_rag: false
  function_calling: false #true #false  # Claude does not support function calling yet
rag:
  k_examples: 4
  embedding_model: "BAAI/bge-m3" # "sentence-transformers/all-MiniLM-L6-v2"
  db_path: "data/vector_db"  # Vector DB save base path
  save_db: true  # Whether to save DB
  load_db: true  # Whether to load existing DB
  
prompt:
  # Detailed prompt
  
  emotion: &emotion_prompt |
    # Emotion Analysis Prompt
    You are an expert in emotion analysis. Given a text input, classify its **primary emotion** strictly as one of the following: **'joy', 'fear', 'anger', 'sadness', 'disgust', 'shame',** or **'guilt'**. **Do not use any other emotions.**
    
    ## Output Format
    Return ONLY a valid JSON object with these exact fields:
    {
      "emotion": "one_of_the_specified_emotions",
      "confidence_score": number_between_0_and_1,
      "explanation": "brief_explanation"
    }
    
    ## Important Rules:
    1. Use ONLY the specified emotions
    2. Return ONLY the JSON object, no other text
    3. Do not include code blocks or formatting
    4. Ensure valid JSON syntax
    
    Now analyze this text:
  emotion_fewshot: &emotion_fewshot |
    # Emotion Analysis Prompt with Examples
    You are an expert in emotion analysis. Given a text input, classify its **primary emotion** strictly as one of the following: **'joy', 'fear', 'anger', 'sadness', 'disgust', 'shame',** or **'guilt'**. **Do not use any other emotions.**
    ---
    ## Instructions

    1. **Read and understand** the input text carefully.
    2. **Strictly classify** the text as one of these **only**: 'joy', 'fear', 'anger', 'sadness', 'disgust', 'shame', or 'guilt'.
    ---

    ## Definitions and Examples

    ### Joy
    - **Definition:** A feeling of happiness, excitement, or pleasure.
    - **Examples:**
    - Receiving good news, celebrating success, spending time with loved ones.
    - Enjoying a meaningful moment with friends or family.
    - **Refinement:** If the text expresses relief rather than happiness, classify it as **joy**.

    ### Fear
    - **Definition:** A response to perceived danger, risk, or uncertainty, often accompanied by anxiety, nervousness, or distress.
    - **Examples:**
    - Experiencing a sudden scare or physical danger (e.g., a traffic accident, being chased).
    - Worrying about an uncertain future or an important exam.
    - Feeling vulnerable in an unfamiliar or threatening environment.
    - Hearing about a serious illness or personal risk (e.g., medical tests, a pandemic).
    - Imagining a loved one being in danger.
    - Being caught in a situation where you have **no control**.
    - **Refinements:**
    - If the emotion is about loss, classify as **sadness**.
    - If the emotion is about remorse for past actions, classify as **guilt**.

    ### Anger
    - **Definition:** A feeling of irritation, frustration, or rage in response to a perceived injustice, wrongdoing, or moral outrage.
    - **Examples:**
    - Witnessing someone being treated unfairly.
    - Feeling ignored, rejected, or ridiculed.
    - Seeing cruelty, unethical behavior, or injustice.
    - Facing obstacles due to someone else's irresponsibility.
    - Experiencing personal attacks or insults.
    - Dealing with broken promises or betrayal.
    - Encountering discrimination or invasion of personal boundaries.
    - **Refinement:** If the text shows resentment or frustration, classify as **anger**; if it expresses grief or emotional pain, classify as **sadness**.

    ### Sadness
    - **Definition:** A feeling of deep sorrow, grief, or loss, often associated with disappointment, longing, or emotional pain.
    - **Examples:**
    - Losing a loved one, pet, or cherished relationship.
    - Feeling lonely or disconnected.
    - Experiencing personal failure or missed opportunities.
    - Witnessing suffering or misfortune of others.
    - Regretting something that cannot be changed.
    - Feeling rejected or abandoned.
    - Nostalgia for better times.
    - Social isolation or exclusion.
    - Empathy for others' suffering.
    - **Refinements:**
    - If the emotion is regret about one's own actions, classify as **guilt**.
    - If it is about loss or despair, classify as **sadness**.
    - If the response is due to injustice or frustration, classify as **anger**.

    ### Disgust
    - **Definition:** A strong aversion, repulsion, or deep-seated rejection toward something perceived as offensive, impure, unethical, or physically revolting.
    - **Examples:**
    - Seeing animals or people being mistreated.
    - Reading about unethical political actions or human rights violations.
    - Witnessing something grotesque or disturbing.
    - Feeling sickened by someone's behavior (e.g., lying, cheating, betrayal).
    - Encountering unclean, unhygienic, or repulsive physical conditions.
    - **Refinements:**
    - If the reaction is about personal danger, classify as **fear**.
    - If it is about moral or physical revulsion, classify as **disgust**.
    - If the feeling is self-directed regarding a moral failing, classify as **guilt**.

    ### Shame
    - **Definition:** A feeling of humiliation or distress caused by the awareness of wrongdoing or foolish behavior, often accompanied by embarrassment, dishonor, or exposure to judgment.
    - **Examples:**
    - Feeling exposed or judged for personal flaws or mistakes.
    - Experiencing social disapproval or loss of reputation.
    - Being caught in acts of dishonesty or deceit.
    - Violating personal or cultural values, leading to feelings of unworthiness.
    - **Refinements:**
    - If the emotion focuses on feeling judged or humiliated without explicit remorse for harm, classify as **shame**.
    - If the emotion includes explicit remorse for harming someone, classify as **guilt**.

    ### Guilt
    - **Definition:** A feeling of remorse or regret over actions that have harmed others or violated moral principles, focused on personal responsibility rather than external judgment.
    - **Examples:**
    - Feeling bad for hurting someone's feelings.
    - Regretting a past mistake or unethical action.
    - Realizing that one's negligence caused harm.
    - Breaking a rule and later feeling remorseful.
    - **Refinements:**
    - Only classify as **guilt** if there is explicit harm or clear wrongdoing causing remorse.
    - If there is no explicit harm mentioned, default to **shame**.
    - Increase the threshold for guilt; use it only when clear personal responsibility for harm is evident.

    ---

    ## Additional Guidelines:
    - **Default to Shame:** When the text does not explicitly show remorse for an action but hints at personal inadequacy, classify as **shame**.
    - **Mixed Cases:** Evaluate the overall tone and select the most prominent emotion.
    - **Confidence Scoring:** Assign a confidence score between `0` and `1` based on your certainty. If confidence is below `0.6`, lean toward **shame** or **sadness**.
    - **Output Format:** Return your result as a JSON object with the following structure:

    ```json
    {
      "emotion": "one_of_the_specified_emotions",
      "confidence_score": confidence_value,
      "explanation": "brief_explanation"
    }
    ```

    Now, analyze the text, and output only the JSON response with no additional formatting, code blocks, or explanations.
    Text:
  emotion_fewshot_reverse: &emotion_fewshot_reverse |
    # Emotion Analysis Prompt with Examples
    You are an expert in emotion analysis. Given a text input, classify its **primary emotion** strictly as one of the following: **'joy', 'fear', 'anger', 'sadness', 'disgust', 'shame',** or **'guilt'**. **Do not use any other emotions.**
    ---
    ## Instructions

    1. **Read and understand** the input text carefully.
    2. **Strictly classify** the text as one of these **only**: 'joy', 'fear', 'anger', 'sadness', 'disgust', 'shame', or 'guilt'.
    ---

    ## Definitions and Examples
    
    ### Guilt
    - **Definition:** A feeling of remorse or regret over actions that have harmed others or violated moral principles, focused on personal responsibility rather than external judgment.
    - **Examples:**
    - Feeling bad for hurting someone's feelings.
    - Regretting a past mistake or unethical action.
    - Realizing that one's negligence caused harm.
    - Breaking a rule and later feeling remorseful.
    - **Refinements:**
    - Only classify as **guilt** if there is explicit harm or clear wrongdoing causing remorse.
    - If there is no explicit harm mentioned, default to **shame**.
    - Increase the threshold for guilt; use it only when clear personal responsibility for harm is evident.
    
    ### Shame
    - **Definition:** A feeling of humiliation or distress caused by the awareness of wrongdoing or foolish behavior, often accompanied by embarrassment, dishonor, or exposure to judgment.
    - **Examples:**
    - Feeling exposed or judged for personal flaws or mistakes.
    - Experiencing social disapproval or loss of reputation.
    - Being caught in acts of dishonesty or deceit.
    - Violating personal or cultural values, leading to feelings of unworthiness.
    - **Refinements:**
    - If the emotion focuses on feeling judged or humiliated without explicit remorse for harm, classify as **shame**.
    - If the emotion includes explicit remorse for harming someone, classify as **guilt**.
    
    ### Disgust
    - **Definition:** A strong aversion, repulsion, or deep-seated rejection toward something perceived as offensive, impure, unethical, or physically revolting.
    - **Examples:**
    - Seeing animals or people being mistreated.
    - Reading about unethical political actions or human rights violations.
    - Witnessing something grotesque or disturbing.
    - Feeling sickened by someone's behavior (e.g., lying, cheating, betrayal).
    - Encountering unclean, unhygienic, or repulsive physical conditions.
    - **Refinements:**
    - If the reaction is about personal danger, classify as **fear**.
    - If it is about moral or physical revulsion, classify as **disgust**.
    - If the feeling is self-directed regarding a moral failing, classify as **guilt**.

    ### Sadness
    - **Definition:** A feeling of deep sorrow, grief, or loss, often associated with disappointment, longing, or emotional pain.
    - **Examples:**
    - Losing a loved one, pet, or cherished relationship.
    - Feeling lonely or disconnected.
    - Experiencing personal failure or missed opportunities.
    - Witnessing suffering or misfortune of others.
    - Regretting something that cannot be changed.
    - Feeling rejected or abandoned.
    - Nostalgia for better times.
    - Social isolation or exclusion.
    - Empathy for others' suffering.
    - **Refinements:**
    - If the emotion is regret about one's own actions, classify as **guilt**.
    - If it is about loss or despair, classify as **sadness**.
    - If the response is due to injustice or frustration, classify as **anger**.

    ### Anger
    - **Definition:** A feeling of irritation, frustration, or rage in response to a perceived injustice, wrongdoing, or moral outrage.
    - **Examples:**
    - Witnessing someone being treated unfairly.
    - Feeling ignored, rejected, or ridiculed.
    - Seeing cruelty, unethical behavior, or injustice.
    - Facing obstacles due to someone else's irresponsibility.
    - Experiencing personal attacks or insults.
    - Dealing with broken promises or betrayal.
    - Encountering discrimination or invasion of personal boundaries.
    - **Refinement:** If the text shows resentment or frustration, classify as **anger**; if it expresses grief or emotional pain, classify as **sadness**.

    ### Fear
    - **Definition:** A response to perceived danger, risk, or uncertainty, often accompanied by anxiety, nervousness, or distress.
    - **Examples:**
    - Experiencing a sudden scare or physical danger (e.g., a traffic accident, being chased).
    - Worrying about an uncertain future or an important exam.
    - Feeling vulnerable in an unfamiliar or threatening environment.
    - Hearing about a serious illness or personal risk (e.g., medical tests, a pandemic).
    - Imagining a loved one being in danger.
    - Being caught in a situation where you have **no control**.
    - **Refinements:**
    - If the emotion is about loss, classify as **sadness**.
    - If the emotion is about remorse for past actions, classify as **guilt**.

    ### Joy
    - **Definition:** A feeling of happiness, excitement, or pleasure.
    - **Examples:**
    - Receiving good news, celebrating success, spending time with loved ones.
    - Enjoying a meaningful moment with friends or family.
    - **Refinement:** If the text expresses relief rather than happiness, classify it as **joy**.

    ---

    ## Additional Guidelines:
    - **Default to Shame:** When the text does not explicitly show remorse for an action but hints at personal inadequacy, classify as **shame**.
    - **Mixed Cases:** Evaluate the overall tone and select the most prominent emotion.
    - **Confidence Scoring:** Assign a confidence score between `0` and `1` based on your certainty. If confidence is below `0.6`, lean toward **shame** or **sadness**.
    - **Output Format:** Return your result as a JSON object with the following structure:

    ```json
    {
      "emotion": "one_of_the_specified_emotions",
      "confidence_score": confidence_value,
      "explanation": "brief_explanation"
    }
    ```

    Now, analyze the text, and output only the JSON response with no additional formatting, code blocks, or explanations.
    Text:

  # Basic prompt (used when use_template is false)
  template_default: *emotion_fewshot

# # Model prompt mapping
# qwen2.5: *emotion_fewshot
# llama3.2: *emotion_fewshot
# emotion-llama: *emotion_fewshot
# emotion-qwen: *emotion_fewshot
# gpt-3.5-turbo: *emotion_prompt
# solar-1-mini-chat: *emotion_prompt #*emotion_fewshot
# claude-3-sonnet-20240229: *emotion_prompt #*emotion_fewshot  # Update model name mapping
# hf.co/tensorblock/Emotion-LLaMA-GGUF: *emotion_fewshot # *emotion_fewshot
# sebdg/emotional_llama: *emotion_fewshot
# deepseek-r1: *emotion_fewshot
# gemma2: *emotion_fewshot

